version: "3.9"

x-client-base: &client-base
  build:
    context: ../
    dockerfile: iac/client/Dockerfile
  image: eaglechat-client
  networks:
    - eaglechat-net
  depends_on:
    - id-manager-1
  environment:
    ID_MANAGER_ENDPOINTS: ${ID_MANAGER_ENDPOINTS}
  stdin_open: true
  tty: true

networks:
  eaglechat-net:
    driver: overlay
    attachable: true

services:
  id-manager-1:
    build:
      context: ../
      dockerfile: iac/id_manager/Dockerfile
    image: eaglechat-id-manager
    networks:
      eaglechat-net:
        aliases:
          - id_manager.eaglechat.local
    secrets:
      - ca_key
      - ca_cert
    environment:
      CA_KEY_PATH: /run/secrets/ca_key
      CA_CERT_PATH: /run/secrets/ca_cert
      COMMON_NAME: id-manager-1.eaglechat.local # Unique common name

  id-manager-2:
    build:
      context: ../
      dockerfile: iac/id_manager/Dockerfile
    image: eaglechat-id-manager
    networks:
      eaglechat-net:
        aliases:
          - id_manager.eaglechat.local
    profiles:
      - "multi-manager"
    secrets:
      - ca_key
      - ca_cert
    environment:
      CA_KEY_PATH: /run/secrets/ca_key
      CA_CERT_PATH: /run/secrets/ca_cert
      COMMON_NAME: id-manager-2.eaglechat.local # Unique common name

  client-1:
    <<: *client-base

  client-2:
    <<: *client-base

  client-3:
    <<: *client-base

secrets:
  ca_key:
    file: ../ca.key
  ca_cert:
    file: ../ca.crt
