version: "3.9"

x-client-base: &client-base
  build:
    context: ../
    dockerfile: iac/client/Dockerfile
  image: eaglechat-client
  networks:
    - eaglechat-net
  depends_on:
    - id-manager-1
  environment:
    ID_MANAGER_ENDPOINTS: ${ID_MANAGER_ENDPOINTS}
    CA_PUBLIC_KEY_PATH: /etc/eaglechat/common_ca/ca_public_key.pem
    TZ: ${TZ:-America/Havana}
    LANG: ${LANG:-en_US.UTF-8}
  volumes:
    - ./tmp_certs/id-manager-1:/etc/eaglechat/certs:ro
    - ./tmp_certs/common_ca:/etc/eaglechat/common_ca:ro
  stdin_open: true
  tty: true

networks:
  eaglechat-net:
    driver: overlay
    attachable: true

services:
  id-manager-1:
    build:
      context: ../
      dockerfile: iac/id_manager/Dockerfile
    image: eaglechat-id-manager
    networks:
      eaglechat-net:
        aliases:
          - id_manager.eaglechat.local
    volumes:
      - ./tmp_certs/id-manager-1:/etc/eaglechat/certs:ro
      - ./tmp_certs/common_ca:/etc/eaglechat/common_ca:ro
    environment:
      ID_MANAGER_PRIV_KEY_PATH: /etc/eaglechat/certs/private_key.pem
      ID_MANAGER_SIGNATURE_PATH: /etc/eaglechat/certs/id_manager_signature.pem
      CA_PUBLIC_KEY_PATH: /etc/eaglechat/common_ca/ca_public_key.pem
      COMMON_NAME: id-manager-1.eaglechat.local

  id-manager-2:
    build:
      context: ../
      dockerfile: iac/id_manager/Dockerfile
    image: eaglechat-id-manager
    networks:
      eaglechat-net:
        aliases:
          - id_manager.eaglechat.local
    profiles:
      - "multi-manager"
    volumes:
      - ./tmp_certs/id-manager-2:/etc/eaglechat/certs:ro
      - ./tmp_certs/common_ca:/etc/eaglechat/common_ca:ro
    environment:
      ID_MANAGER_PRIV_KEY_PATH: /etc/eaglechat/certs/private_key.pem
      ID_MANAGER_SIGNATURE_PATH: /etc/eaglechat/certs/id_manager_signature.pem
      CA_PUBLIC_KEY_PATH: /etc/eaglechat/common_ca/ca_public_key.pem
      COMMON_NAME: id-manager-2.eaglechat.local

  client-1:
    <<: *client-base

  client-2:
    <<: *client-base

  client-3:
    <<: *client-base
